dataset:
  tfrecords_pattern: "data/processed/*.tfrecord"
  batch_size: 4
  sequence_length: 128
  temporal_window: 30
  tabular_dim: 15

model:
  local_hf_path: "models/local_hf_weights/distilbert-base-uncased"
  vision_embedding_dim: 128
  text_embedding_dim: 128
  temporal_embedding_dim: 128
  tabular_embedding_dim: 64

training:
  epochs: 1
  batch_size: 4
  learning_rate: 0.0001
  mixed_precision: true
  model_dir: "models/checkpoints/"